-- USER TABLES
CREATE TABLE User (
    User_ID INT PRIMARY KEY AUTO_INCREMENT,
    Fname VARCHAR(100) NOT NULL,
    Lname VARCHAR(100) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Phone VARCHAR(20),
    Password VARCHAR(255) NOT NULL,
    Image LONGBLOB,
    User_Description TEXT,
    Status ENUM('Suspended', 'Blocked', 'Active') DEFAULT 'Active',
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Wallet (
    Wallet_ID INT PRIMARY KEY AUTO_INCREMENT,
    User_ID INT NOT NULL UNIQUE,
    Balance DECIMAL(10, 2) DEFAULT 0,
    FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE
);

-- BOOTH TABLES
CREATE TABLE Booth (
    Booth_ID INT PRIMARY KEY AUTO_INCREMENT,
    User_ID INT NOT NULL UNIQUE,
    Name VARCHAR(255) NOT NULL,
    Description TEXT,
    Image LONGBLOB,
    Account_No VARCHAR(50),
    Student_Card_Image LONGBLOB,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE
);

CREATE TABLE Employee (
    Employee_ID INT PRIMARY KEY AUTO_INCREMENT,
    Booth_ID INT NOT NULL,
    Fname VARCHAR(100) NOT NULL,
    Lname VARCHAR(100) NOT NULL,
    Perm_No INT DEFAULT 0,
    Start_Date DATE NOT NULL,
    End_Date DATE,
    FOREIGN KEY (Booth_ID) REFERENCES Booth(Booth_ID) ON DELETE CASCADE
);

-- PRODUCT TABLES
CREATE TABLE Product (
    Product_ID INT PRIMARY KEY AUTO_INCREMENT,
    Booth_ID INT NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Description TEXT,
    Image LONGBLOB,
    Stock_Quantity INT DEFAULT 0,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Booth_ID) REFERENCES Booth(Booth_ID) ON DELETE CASCADE
);

CREATE TABLE Price_History (
    Price_History_ID INT PRIMARY KEY AUTO_INCREMENT,
    Product_ID INT NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Unit VARCHAR(50),
    Valid_from DATE NOT NULL,
    Valid_to DATE,
    FOREIGN KEY (Product_ID) REFERENCES Product(Product_ID) ON DELETE CASCADE
);

-- SERVICE TABLES
CREATE TABLE Service (
    Service_ID INT PRIMARY KEY AUTO_INCREMENT,
    Booth_ID INT NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Description TEXT,
    Image LONGBLOB,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Booth_ID) REFERENCES Booth(Booth_ID) ON DELETE CASCADE
);

CREATE TABLE Time_Table (
    Time_Table_ID INT PRIMARY KEY AUTO_INCREMENT,
    Service_ID INT NOT NULL,
    Service_Time VARCHAR(100),
    Start_Time TIME NOT NULL,
    End_Time TIME NOT NULL,
    FOREIGN KEY (Service_ID) REFERENCES Service(Service_ID) ON DELETE CASCADE
);

CREATE TABLE Good (
    Good_ID INT PRIMARY KEY AUTO_INCREMENT,
    Service_ID INT NOT NULL,
    Booth_ID INT NOT NULL,
    Name VARCHAR(255),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Service_ID) REFERENCES Service(Service_ID) ON DELETE CASCADE,
    FOREIGN KEY (Booth_ID) REFERENCES Booth(Booth_ID) ON DELETE CASCADE
);

-- ORDER TABLES
CREATE TABLE `Order` (
    Order_ID INT PRIMARY KEY AUTO_INCREMENT,
    User_ID INT NOT NULL,
    Order_Date DATETIME NOT NULL,
    Total_Amount DECIMAL(10, 2) NOT NULL,
    Status ENUM('Pending', 'Paid', 'Shipped', 'Delivered', 'Cancelled') DEFAULT 'Pending',
    Tracking_Code VARCHAR(100),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE
);

CREATE TABLE Order_Item (
    OrderItem_ID INT PRIMARY KEY AUTO_INCREMENT,
    Order_ID INT NOT NULL,
    Product_ID INT NOT NULL,
    Unit_Price DECIMAL(10, 2) NOT NULL,
    Quantity INT NOT NULL,
    Status ENUM('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled') DEFAULT 'Pending',
    FOREIGN KEY (Order_ID) REFERENCES `Order`(Order_ID) ON DELETE CASCADE,
    FOREIGN KEY (Product_ID) REFERENCES Product(Product_ID) ON DELETE RESTRICT
);

-- PAYMENT TABLES
CREATE TABLE Payment (
    Payment_ID INT PRIMARY KEY AUTO_INCREMENT,
    Order_ID INT NOT NULL UNIQUE,
    Payment_Date DATETIME NOT NULL,
    Amount DECIMAL(10, 2) NOT NULL,
    Payment_Method ENUM('Online', 'Wallet') NOT NULL,
    Payment_Status ENUM('Success', 'Failed', 'Pending') DEFAULT 'Pending',
    Transaction_Ref VARCHAR(100) UNIQUE,
    FOREIGN KEY (Order_ID) REFERENCES `Order`(Order_ID) ON DELETE CASCADE
);

-- SHIPMENT TABLES
CREATE TABLE Shipment (
    Shipment_ID INT PRIMARY KEY AUTO_INCREMENT,
    Order_ID INT NOT NULL,
    Shipment_Date DATETIME NOT NULL,
    Shipment_Method VARCHAR(100),
    Receiver_Name VARCHAR(255) NOT NULL,
    Receiver_Phone VARCHAR(20) NOT NULL,
    Street VARCHAR(255),
    City VARCHAR(100),
    Province VARCHAR(100),
    Postal_Code VARCHAR(20),
    FOREIGN KEY (Order_ID) REFERENCES `Order`(Order_ID) ON DELETE CASCADE
);

-- DISCOUNT TABLES
CREATE TABLE Discount_Code (
    Discount_Code_ID INT PRIMARY KEY AUTO_INCREMENT,
    Code VARCHAR(100) UNIQUE NOT NULL,
    Type ENUM('Fixed', 'Percentage') NOT NULL,
    Amount DECIMAL(10, 2),
    Percent DECIMAL(5, 2),
    Start_Date DATE NOT NULL,
    Expiration_Date DATE NOT NULL,
    Status ENUM('Active', 'Suspended', 'Blocked') DEFAULT 'Active',
    Is_Used BOOLEAN DEFAULT FALSE
);

CREATE TABLE Discount_Usage (
    Usage_ID INT PRIMARY KEY AUTO_INCREMENT,
    Discount_Code_ID INT NOT NULL,
    Order_ID INT NOT NULL,
    Used_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Discount_Code_ID) REFERENCES Discount_Code(Discount_Code_ID) ON DELETE CASCADE,
    FOREIGN KEY (Order_ID) REFERENCES `Order`(Order_ID) ON DELETE CASCADE
);

-- CART TABLES
CREATE TABLE Cart (
    Cart_ID INT PRIMARY KEY AUTO_INCREMENT,
    User_ID INT NOT NULL UNIQUE,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE
);

CREATE TABLE Cart_Item (
    Cart_Item_ID INT PRIMARY KEY AUTO_INCREMENT,
    Cart_ID INT NOT NULL,
    Product_ID INT NOT NULL,
    Quantity INT NOT NULL,
    Added_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Cart_ID) REFERENCES Cart(Cart_ID) ON DELETE CASCADE,
    FOREIGN KEY (Product_ID) REFERENCES Product(Product_ID) ON DELETE CASCADE
);

CREATE TABLE Locked_Cart (
    Locked_Cart_ID INT PRIMARY KEY AUTO_INCREMENT,
    Cart_ID INT NOT NULL UNIQUE,
    Lock_End_Date DATETIME NOT NULL,
    Final_Amount DECIMAL(10, 2),
    FOREIGN KEY (Cart_ID) REFERENCES Cart(Cart_ID) ON DELETE CASCADE
);

-- REVIEW & COMMENT TABLES
CREATE TABLE Review (
    Review_ID INT PRIMARY KEY AUTO_INCREMENT,
    User_ID INT NOT NULL,
    Product_ID INT,
    Booth_ID INT,
    Rating INT CHECK (Rating >= 1 AND Rating <= 5),
    Comment TEXT,
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE,
    FOREIGN KEY (Product_ID) REFERENCES Product(Product_ID) ON DELETE CASCADE,
    FOREIGN KEY (Booth_ID) REFERENCES Booth(Booth_ID) ON DELETE CASCADE
);

CREATE TABLE Comment (
    Comment_ID INT PRIMARY KEY AUTO_INCREMENT,
    Review_ID INT NOT NULL,
    User_ID INT NOT NULL,
    Comment_Text TEXT NOT NULL,
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Review_ID) REFERENCES Review(Review_ID) ON DELETE CASCADE,
    FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE
);

-- SUPPORT & REQUEST TABLES
CREATE TABLE Support (
    Support_ID INT PRIMARY KEY AUTO_INCREMENT,
    User_ID INT NOT NULL,
    Support_Reason VARCHAR(255),
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status ENUM('Open', 'In_Progress', 'Closed') DEFAULT 'Open',
    FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE
);

CREATE TABLE Page_Request (
    Page_Request_ID INT PRIMARY KEY AUTO_INCREMENT,
    User_ID INT NOT NULL,
    Reason VARCHAR(255),
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending',
    FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE
);

CREATE TABLE Booth_Request (
    Booth_Request_ID INT PRIMARY KEY AUTO_INCREMENT,
    User_ID INT NOT NULL,
    Reason VARCHAR(255),
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending',
    End_Date DATE,
    FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE
);

CREATE TABLE Join_Request (
    Join_Request_ID INT PRIMARY KEY AUTO_INCREMENT,
    User_ID INT NOT NULL,
    Booth_ID INT NOT NULL,
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending',
    FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE,
    FOREIGN KEY (Booth_ID) REFERENCES Booth(Booth_ID) ON DELETE CASCADE
);

-- MESSAGING TABLES
CREATE TABLE Chat (
    Chat_ID INT PRIMARY KEY AUTO_INCREMENT,
    User_ID1 INT NOT NULL,
    User_ID2 INT NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID1) REFERENCES User(User_ID) ON DELETE CASCADE,
    FOREIGN KEY (User_ID2) REFERENCES User(User_ID) ON DELETE CASCADE
);

CREATE TABLE Message (
    Message_ID INT PRIMARY KEY AUTO_INCREMENT,
    Chat_ID INT NOT NULL,
    Sender_ID INT NOT NULL,
    Sender_Type ENUM('User', 'Admin', 'Support'),
    Content TEXT NOT NULL,
    Sent_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Chat_ID) REFERENCES Chat(Chat_ID) ON DELETE CASCADE,
    FOREIGN KEY (Sender_ID) REFERENCES User(User_ID) ON DELETE CASCADE
);

-- BADGE TABLES
CREATE TABLE Badge (
    Badge_ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Description TEXT,
    Image LONGBLOB,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Badge_Approval (
    Badge_Approval_ID INT PRIMARY KEY AUTO_INCREMENT,
    User_ID INT NOT NULL,
    Badge_ID INT NOT NULL,
    Assigned_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE,
    FOREIGN KEY (Badge_ID) REFERENCES Badge(Badge_ID) ON DELETE CASCADE
);

-- VIP TABLES
CREATE TABLE Plan (
    Plan_ID INT PRIMARY KEY AUTO_INCREMENT,
    Plan_Type ENUM('VIP', 'Golden') NOT NULL,
    Name VARCHAR(255),
    Period INT,
    Price DECIMAL(10, 2) NOT NULL,
    Description TEXT
);

CREATE TABLE VIP_Plan (
    VIP_Plan_ID INT PRIMARY KEY AUTO_INCREMENT,
    User_ID INT NOT NULL,
    Plan_ID INT NOT NULL,
    Start_Date DATE NOT NULL,
    End_Date DATE,
    Count INT,
    FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE,
    FOREIGN KEY (Plan_ID) REFERENCES Plan(Plan_ID) ON DELETE RESTRICT
);

CREATE TABLE Golden_Booth (
    Golden_Booth_ID INT PRIMARY KEY AUTO_INCREMENT,
    Booth_ID INT NOT NULL UNIQUE,
    Plan_ID INT NOT NULL,
    Start_Date DATE NOT NULL,
    End_Date DATE,
    FOREIGN KEY (Booth_ID) REFERENCES Booth(Booth_ID) ON DELETE CASCADE,
    FOREIGN KEY (Plan_ID) REFERENCES Plan(Plan_ID) ON DELETE RESTRICT
);

-- STORY & MEDIA TABLES
CREATE TABLE Story (
    Story_ID INT PRIMARY KEY AUTO_INCREMENT,
    Booth_ID INT NOT NULL,
    Content TEXT,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Booth_ID) REFERENCES Booth(Booth_ID) ON DELETE CASCADE
);

CREATE TABLE Picture (
    Picture_ID INT PRIMARY KEY AUTO_INCREMENT,
    Story_ID INT NOT NULL,
    Image LONGBLOB NOT NULL,
    Uploaded_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Story_ID) REFERENCES Story(Story_ID) ON DELETE CASCADE
);

-- BOOKMARK TABLES
CREATE TABLE Bookmark (
    Bookmark_ID INT PRIMARY KEY AUTO_INCREMENT,
    User_ID INT NOT NULL,
    Product_ID INT,
    Booth_ID INT,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE,
    FOREIGN KEY (Product_ID) REFERENCES Product(Product_ID) ON DELETE CASCADE,
    FOREIGN KEY (Booth_ID) REFERENCES Booth(Booth_ID) ON DELETE CASCADE
);

-- EVENT & LOGGING TABLES
CREATE TABLE Event (
    Event_ID INT PRIMARY KEY AUTO_INCREMENT,
    User_ID INT NOT NULL,
    Event_Type ENUM('VIEW_BOOTH', 'VIEW_PRODUCT', 'ADD_TO_CART', 'PURCHASE'),
    Event_Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    Session_ID VARCHAR(100),
    FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE
);

CREATE TABLE Action_Log (
    Log_ID INT PRIMARY KEY AUTO_INCREMENT,
    User_ID INT NOT NULL,
    Action_Type VARCHAR(100) NOT NULL,
    Description TEXT,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    IP_Address VARCHAR(45),
    FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE
);

-- INDEXES for Performance
CREATE INDEX idx_user_email ON User(Email);
CREATE INDEX idx_product_booth ON Product(Booth_ID);
CREATE INDEX idx_order_user ON `Order`(User_ID);
CREATE INDEX idx_review_product ON Review(Product_ID);
CREATE INDEX idx_review_booth ON Review(Booth_ID);
CREATE INDEX idx_cartitem_cart ON Cart_Item(Cart_ID);
CREATE INDEX idx_discount_code ON Discount_Code(Code);
CREATE INDEX idx_message_chat ON Message(Chat_ID);
CREATE INDEX idx_event_user ON Event(User_ID);
